name: CI

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            arch: amd64
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            arch: amd64
          - target: x86_64-apple-darwin
            os: macos-latest
            arch: amd64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install prerequisites for MacOS
        run: |
          brew install libvpx 
        if: startsWith(matrix.os, 'macos-')

      - name: Install prerequisites for Ubuntu
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libvpx-dev libxcb-randr0-dev libxv-dev libvdpau-dev libxcb-shm0-dev
        if: startsWith(matrix.os, 'ubuntu-')

      - name: Install prerequisites for Windows
        run: |
          curl -sSfL -O  https://github.com/ShiftMediaProject/libvpx/releases/download/v1.12.0/libvpx_v1.12.0_msvc16.zip
          unzip libvpx_v1.12.0_msvc16.zip -d $HOME\unzipped
          Add-Content -Path $env:GITHUB_ENV -Value "VPX_STATIC=1"
          Add-Content -Path $env:GITHUB_ENV -Value "VPX_VERSION=1.12.0"
          Add-Content -Path $env:GITHUB_ENV -Value "VPX_LIB_DIR=$HOME\unzipped\lib\x64"
          Add-Content -Path $env:GITHUB_ENV -Value "VPX_INCLUDE_DIR=$HOME\unzipped\include"
        if: startsWith(matrix.os, 'windows-')

      - name: Build
        uses: actions-rs/cargo@v1
        if: matrix.arch != 'arm64'
        with:
          command: build
          args: --release

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-release
          path: target/${{ matrix.target }}/release/*.exe
